# docker-compose.yml
version: '3'
services:
  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server
  server:
    build:
      context: ./server
    ports:
      - "3001:3001"
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
